apiVersion: v1
kind: Pod
metadata: 
 name: node-affinity
spec:
 affinity:
  nodeAffinity:
   #Hard rule
   requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
         - us-east-1c
    #soft rule is optional it will check the priority before scheduling even though the any of these expressions true pod still schedule pod because of hard rule that satisfied with zone.
   preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 10
       preference:
        matchExpressions:
         - key: project
           operator: In
           values:
           - roboshop
     - weight: 1
       preference:
        matchExpressions:
         - key: project
           operator: In
           values:
           - Amazon
           
 containers:
  - name: nginx
    image: nginx


   