apiVersion: v1
kind: Pod
metadata: 
 name: node-anti-affinity
 labels:
  env: test
spec:
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
     - matchExpressions:
       - key: topology.kuberenetes.io/zone
         operator: NotIn
         values:
          - us-east-1c
       - key: project
         operator: NotIn
         values:
         - Amazon
 containers:
   name: nginx
   image: nginx

   